freebsd_task:
  name: "freebsd:12.1"
  freebsd_instance:
    image_family: freebsd-12-1
  env:
    ASSUME_ALWAYS_YES: yes
  script:
    - tools/install-build-pkgs
    - gmake -j4

#macos_task:
#  osx_instance:
#    image: catalina-base
#  script:
#    - tools/install-build-pkgs
#    - gmake -j4

linux_task:
  name: "alpine:3.11"
  container:
    image: alpine:3.11
    cpu: 4
    memory: 2G
  timeout_in: 10m
  script:
    - tools/install-build-pkgs
    - make STATIC=1 LTO=1

linux_task:
  name: "alpine:3.12"
  container:
    image: alpine:3.12
    cpu: 4
    memory: 2G
  timeout_in: 10m
  script:
    - tools/install-build-pkgs
    - make STATIC=1 LTO=1

linux_task:
  name: "centos:7"
  container:
    image: centos:7
    cpu: 4
    memory: 2G
  timeout_in: 10m
  script:
    - tools/install-build-pkgs
    - make
    - make rpm

linux_task:
  name: "centos:8"
  container:
    image: centos:8
    cpu: 4
    memory: 2G
  timeout_in: 10m
  script:
    - tools/install-build-pkgs
    - make
    - make rpm

linux_task:
  name: "fedora:30"
  container:
    image: fedora:30
    cpu: 4
    memory: 2G
  timeout_in: 10m
  script:
    - tools/install-build-pkgs
    - make
    - make rpm

linux_task:
  name: "fedora:31"
  container:
    image: fedora:31
    cpu: 4
    memory: 2G
  timeout_in: 10m
  script:
    - tools/install-build-pkgs
    - make
    - make rpm

linux_task:
  name: "fedora:32"
  container:
    image: fedora:32
    cpu: 4
    memory: 2G
  timeout_in: 10m
  script:
    - tools/install-build-pkgs
    - make
    - make rpm

linux_task:
  name: "fedora:33"
  container:
    image: fedora:33
    cpu: 4
    memory: 2G
  timeout_in: 10m
  script:
    - tools/install-build-pkgs
    - make
    - make rpm

linux_task:
  name: "ubuntu:14.04"
  container:
    image: ubuntu:14.04
    cpu: 4
    memory: 2G
  timeout_in: 10m
  script:
    - tools/install-build-pkgs
    - git fetch
    - make deb
    - apt-get -y install fuse
    - dpkg -i ../*.deb
    - mergerfs -v || true

linux_task:
  name: "ubuntu:16.04"
  container:
    image: ubuntu:16.04
    cpu: 4
    memory: 2G
  timeout_in: 10m
  script:
    - tools/install-build-pkgs
    - git fetch
    - make deb
    - apt-get -y install fuse
    - dpkg -i ../*.deb
    - mergerfs -v || true

linux_task:
  name: "ubuntu:18.04"
  container:
    image: ubuntu:18.04
    cpu: 4
    memory: 2G
  timeout_in: 10m
  script:
    - tools/install-build-pkgs
    - git fetch
    - make deb
    - apt-get -y install fuse
    - dpkg -i ../*.deb
    - mergerfs -v || true

linux_task:
  name: "ubuntu:20.04"
  container:
    image: ubuntu:20.04
    cpu: 4
    memory: 2G
  timeout_in: 10m
  script:
    - tools/install-build-pkgs
    - git fetch
    - make deb
    - apt-get -y install fuse
    - dpkg -i ../*.deb
    - mergerfs -v || true

linux_task:
  name: "debian:7"
  container:
    image: debian:8
    cpu: 4
    memory: 2G
  timeout_in: 10m
  script:
    - tools/install-build-pkgs
    - git fetch
    - make deb
    - apt-get -y install fuse
    - dpkg -i ../*.deb
    - mergerfs -v || true

linux_task:
  name: "debian:8"
  container:
    image: debian:8
    cpu: 4
    memory: 2G
  timeout_in: 10m
  script:
    - tools/install-build-pkgs
    - git fetch
    - make deb
    - apt-get -y install fuse
    - dpkg -i ../*.deb
    - mergerfs -v || true

linux_task:
  name: "debian:9"
  container:
    image: debian:9
    cpu: 4
    memory: 2G
  timeout_in: 10m
  script:
    - tools/install-build-pkgs
    - git fetch
    - make deb
    - apt-get -y install fuse
    - dpkg -i ../*.deb
    - mergerfs -v || true

linux_task:
  name: "debian:10"
  container:
    image: debian:10
    cpu: 4
    memory: 2G
  timeout_in: 10m
  script:
    - tools/install-build-pkgs
    - git fetch
    - make deb
    - apt-get -y install fuse
    - dpkg -i ../*.deb
    - mergerfs -v || true
