linux_task:
  name: "alpine:latest"
  container:
    image: alpine:latest
    cpu: 4
    memory: 4G
  timeout_in: 15m
  script:
    - buildtools/install-build-pkgs
    - make STATIC=1 LTO=1

linux_task:
  name: "alpine-arm:latest"
  arm_container:
    image: alpine:latest
    cpu: 4
    memory: 4G
  timeout_in: 15m
  script:
    - buildtools/install-build-pkgs
    - make STATIC=1 LTO=1

linux_task:
  name: "fedora:41"
  container:
    image: fedora:41
    cpu: 4
    memory: 4G
  timeout_in: 15m
  script:
    - buildtools/install-build-pkgs
    - make
    - make rpm

linux_task:
  name: "fedora-arm:41"
  arm_container:
    image: fedora:41
    cpu: 4
    memory: 4G
  timeout_in: 15m
  script:
    - buildtools/install-build-pkgs
    - make
    - make rpm

linux_task:
  name: "ubuntu:22.04"
  container:
    image: ubuntu:22.04
    cpu: 4
    memory: 4G
  timeout_in: 15m
  script:
    - buildtools/install-build-pkgs
    - git fetch
    - make deb
    - apt-get -y install fuse
    - dpkg -i ../*.deb
    - mergerfs -v || true

linux_task:
  name: "ubuntu:24.04"
  container:
    image: ubuntu:24.04
    cpu: 4
    memory: 4G
  timeout_in: 15m
  script:
    - buildtools/install-build-pkgs
    - git fetch
    - make deb
    - apt-get -y install fuse
    - dpkg -i ../*.deb
    - mergerfs -v || true

linux_task:
  name: "ubuntu:latest"
  container:
    image: ubuntu:latest
    cpu: 4
    memory: 4G
  timeout_in: 15m
  script:
    - buildtools/install-build-pkgs
    - git fetch
    - make deb
    - apt-get -y install fuse
    - dpkg -i ../*.deb
    - mergerfs -v || true

linux_task:
  name: "ubuntu-arm:latest"
  arm_container:
    image: ubuntu:latest
    cpu: 4
    memory: 4G
  timeout_in: 15m
  script:
    - buildtools/install-build-pkgs
    - git fetch
    - make deb
    - apt-get -y install fuse
    - dpkg -i ../*.deb
    - mergerfs -v || true

linux_task:
  name: "debian:12"
  container:
    image: debian:12
    cpu: 4
    memory: 4G
  timeout_in: 15m
  script:
    - buildtools/install-build-pkgs
    - git fetch
    - make deb
    - apt-get -y install fuse
    - dpkg -i ../*.deb
    - mergerfs -v || true

linux_task:
  name: "debian:latest"
  container:
    image: debian:latest
    cpu: 4
    memory: 4G
  timeout_in: 15m
  script:
    - buildtools/install-build-pkgs
    - git fetch
    - make deb
    - apt-get -y install fuse
    - dpkg -i ../*.deb
    - mergerfs -v || true

linux_task:
  name: "debian-arm:latest"
  arm_container:
    image: debian:latest
    cpu: 4
    memory: 4G
  timeout_in: 15m
  script:
    - buildtools/install-build-pkgs
    - git fetch
    - make deb
    - apt-get -y install fuse
    - dpkg -i ../*.deb
    - mergerfs -v || true
