#!/bin/sh
set -e

if [ $# -ne 2 ]; then
    echo "usage: $0 <branch> <git_repo>"
    echo "argv: $@"
    echo "argc: $#"
    exit 1
fi

GIT_REPO="${1}"
BRANCH="${2}"
BUILDDIR="/tmp/build"

echo "Clone source from ${GIT_REPO} to ${BUILDDIR}"
git \
    clone \
    --single-branch \
    --branch="${BRANCH}" \
    "${GIT_REPO}" \
    "${BUILDDIR}"

cd "${BUILDDIR}"

git log HEAD^1..

mkdir "/build"
if [ -e /usr/bin/apt-get ]; then
    make deb
elif [ -e /usr/bin/dnf ]; then
    make rpm
elif [ -e /usr/bin/yum ]; then
    . /opt/rh/devtoolset-9/enable
    make rpm
elif [ -e /sbin/apk ]; then
    echo "NOT YET SUPPORTED"
    exit 1
elif [ -e /usr/sbin/pkg ]; then
    echo "NOT YET SUPPORTED"
    exit 1
else
    echo "NOT YET SUPPORTED"
    exit 1
fi

echo "Copy packages to host..."
find "${BUILDDIR}" \
     -type f \
     \( -name "*.deb" -or -name "*.rpm" \) \
     -not -name "*dbgsym*" \
     -not -name "*sym*" \
     -not -name "*src.rpm" \
     -exec cp -v {} /build/ \;

exit 0
