#!/usr/bin/env python3

import os
import stat
import sys
import tempfile

from posix_parity import cleanup_dir
from posix_parity import cleanup_paths
from posix_parity import compare_calls
from posix_parity import fail
from posix_parity import join
from posix_parity import mergerfs_mount
from posix_parity import temp_dir


def main():
    try:
        with mergerfs_mount() as (mount, _):
            with tempfile.TemporaryDirectory() as native:
                merge_base = temp_dir(mount)
                try:
                    native_base = join(native, os.path.basename(merge_base))
                    os.makedirs(native_base, exist_ok=True)

                    merge_file = join(merge_base, "file")
                    native_file = join(native_base, "file")
                    merge_exist = join(merge_base, "exist")
                    native_exist = join(native_base, "exist")
                    merge_notdir = join(merge_base, "notdir")
                    native_notdir = join(native_base, "notdir")

                    cleanup_paths([merge_file, merge_exist, merge_notdir])

                    err = compare_calls(
                        "create success",
                        lambda: os.open(merge_file, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o640),
                        lambda: os.open(native_file, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o640),
                        close_fds=True,
                    )
                    if err:
                        return fail(err)

                    with open(merge_exist, "wb"):
                        pass
                    with open(native_exist, "wb"):
                        pass

                    err = compare_calls(
                        "create EEXIST",
                        lambda: os.open(merge_exist, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o640),
                        lambda: os.open(native_exist, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o640),
                        close_fds=True,
                    )
                    if err:
                        return fail(err)

                    with open(merge_notdir, "wb"):
                        pass
                    with open(native_notdir, "wb"):
                        pass

                    err = compare_calls(
                        "create ENOTDIR",
                        lambda: os.open(join(merge_notdir, "child"), os.O_CREAT | os.O_WRONLY, 0o640),
                        lambda: os.open(join(native_notdir, "child"), os.O_CREAT | os.O_WRONLY, 0o640),
                    )
                    if err:
                        return fail(err)

                    merge_node = join(merge_base, "mknod")
                    native_node = join(native_base, "mknod")
                    cleanup_paths([merge_node])

                    err = compare_calls(
                        "mknod regular",
                        lambda: os.mknod(merge_node, stat.S_IFREG | 0o600, 0),
                        lambda: os.mknod(native_node, stat.S_IFREG | 0o600, 0),
                    )
                    if err:
                        return fail(err)

                    err = compare_calls(
                        "mknod EEXIST",
                        lambda: os.mknod(merge_node, stat.S_IFREG | 0o600, 0),
                        lambda: os.mknod(native_node, stat.S_IFREG | 0o600, 0),
                    )
                    if err:
                        return fail(err)

                    return 0
                finally:
                    cleanup_dir(merge_base)
    except RuntimeError as exc:
        print(str(exc), end="")
        return 77


if __name__ == "__main__":
    raise SystemExit(main())
