#!/usr/bin/env python3

import os
import sys
import tempfile

from posix_parity import cleanup_paths
from posix_parity import compare_calls
from posix_parity import fail
from posix_parity import join
from posix_parity import touch


def main():
    if len(sys.argv) != 2:
        print("usage: TEST_posix_unlink_rename <mountpoint>", file=sys.stderr)
        return 1

    mount = sys.argv[1]

    with tempfile.TemporaryDirectory() as native:
        merge_a = join(mount, "posix-unlink-rename/a")
        native_a = join(native, "posix-unlink-rename/a")
        merge_b = join(mount, "posix-unlink-rename/b")
        native_b = join(native, "posix-unlink-rename/b")
        merge_missing = join(mount, "posix-unlink-rename/missing")
        native_missing = join(native, "posix-unlink-rename/missing")
        merge_notdir = join(mount, "posix-unlink-rename/notdir")
        native_notdir = join(native, "posix-unlink-rename/notdir")

        cleanup_paths([merge_a, merge_b, merge_notdir])
        touch(merge_a, b"a")
        touch(native_a, b"a")

        err = compare_calls("unlink success", lambda: os.unlink(merge_a), lambda: os.unlink(native_a))
        if err:
            return fail(err)

        err = compare_calls("unlink ENOENT", lambda: os.unlink(merge_missing), lambda: os.unlink(native_missing))
        if err:
            return fail(err)

        touch(merge_a, b"a")
        touch(native_a, b"a")
        touch(merge_b, b"b")
        touch(native_b, b"b")

        err = compare_calls("rename overwrite", lambda: os.rename(merge_a, merge_b), lambda: os.rename(native_a, native_b))
        if err:
            return fail(err)

        err = compare_calls("rename ENOENT", lambda: os.rename(merge_missing, merge_a), lambda: os.rename(native_missing, native_a))
        if err:
            return fail(err)

        touch(merge_notdir, b"x")
        touch(native_notdir, b"x")
        err = compare_calls(
            "rename ENOTDIR",
            lambda: os.rename(join(merge_notdir, "child"), merge_a),
            lambda: os.rename(join(native_notdir, "child"), native_a),
        )
        if err:
            return fail(err)

        return 0


if __name__ == "__main__":
    raise SystemExit(main())
