#!/usr/bin/env python3

import os
import sys
import tempfile

(fd,filepath) = tempfile.mkstemp(dir=sys.argv[1])

x = os.lstat(filepath)
x = os.fstat(fd)

os.unlink(filepath)

y = os.fstat(fd)

os.close(fd)
