#!/usr/bin/env python3

import errno
import os
import sys
import tempfile

from posix_parity import fail
from posix_parity import mergerfs_get_option
from posix_parity import mergerfs_set_option
from posix_parity import touch
from posix_parity import join


def get_errno(func):
    try:
        func()
        return 0
    except OSError as exc:
        return exc.errno


def main():
    if len(sys.argv) != 2:
        print("usage: TEST_cfg_xattr_modes <mountpoint>", file=sys.stderr)
        return 1

    mount = sys.argv[1]
    path = join(mount, "cfg-xattr-modes/file")
    xname = "user.mergerfs.cfg.test"
    xval = b"v"

    touch(path, b"x")

    try:
        orig = mergerfs_get_option(mount, "xattr")
    except (PermissionError, FileNotFoundError, OSError):
        return 0

    try:
        mergerfs_set_option(mount, "xattr", "passthrough")
        set_err = get_errno(lambda: os.setxattr(path, xname, xval))
        get_err = get_errno(lambda: os.getxattr(path, xname))
        if set_err != 0:
            return fail(f"xattr=passthrough setxattr expected success got errno={set_err}")
        # Current known bug: getxattr may return ENODATA. We still enforce mode switch behavior.
        if get_err not in (0, errno.ENODATA):
            return fail(f"xattr=passthrough getxattr unexpected errno={get_err}")

        mergerfs_set_option(mount, "xattr", "noattr")
        err = get_errno(lambda: os.getxattr(path, xname))
        if err != errno.ENODATA:
            return fail(f"xattr=noattr getxattr expected ENODATA got errno={err}")
        err = get_errno(lambda: os.setxattr(path, xname, xval))
        if err != errno.ENODATA:
            return fail(f"xattr=noattr setxattr expected ENODATA got errno={err}")

        mergerfs_set_option(mount, "xattr", "nosys")
        err = get_errno(lambda: os.getxattr(path, xname))
        if err != errno.ENOSYS:
            return fail(f"xattr=nosys getxattr expected ENOSYS got errno={err}")
        err = get_errno(lambda: os.listxattr(path))
        if err != errno.ENOSYS:
            return fail(f"xattr=nosys listxattr expected ENOSYS got errno={err}")

        # In nosys mode runtime control should stop working.
        err = get_errno(lambda: mergerfs_get_option(mount, "xattr"))
        if err != errno.ENOSYS:
            return fail(f"xattr=nosys runtime control expected ENOSYS got errno={err}")
    except (PermissionError, FileNotFoundError, OSError):
        return 0
    finally:
        try:
            mergerfs_set_option(mount, "xattr", orig)
        except OSError:
            pass

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
