#!/bin/sh

CXX="${CXX:-c++}"
FUSE_CFLAGS="$(pkg-config --cflags fuse) -DFUSE_USE_VERSION=29"

echo "#include <fuse.h>" | ${CXX} -E ${FUSE_CFLAGS} - | grep "${1}" > /dev/null

[ "$?" != "0" ]; echo $?
